[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "target-feature=+bulk-memory,+mutable-globals,+atomics,+simd128",
    "-C",
    "link-arg=--shared-memory",
    "-C",
    "link-arg=--import-memory",
    "-C",
    "link-arg=--no-check-features",
    "-C",
    "link-arg=--export=__heap_base",
    "-C",
    "link-arg=--export=__data_end",
    "-C",
    "link-arg=--export=__wasm_init_tls",
    "-C",
    "link-arg=--export=__tls_base",
    "-C",
    "link-arg=--export=__tls_size",
    "-C",
    "link-arg=--export=__tls_align",
]

[unstable]
build-std = ["panic_abort", "std"]
